using Maths;
using Conditions;
using Loop;
using IO;
using Arrays;
using Str;
using OOPA;
using OOPC;
using Ladder._09._OOP_C;
using EnumException;

MathRun mathRun = new MathRun();
ConditionRun conRun = new ConditionRun();
LoopRun loopRun = new LoopRun();
IORun ioRun = new IORun();
ArrayRun arRun = new ArrayRun();
StringRun strRun = new StringRun();
new MethodOverriding().SayHi();
//new ThisKeyword().Play();
OperatorOverloading.Play();
LooselyCouplingRun.Play();
YeildKeyword.Play();
EnumTest.Play();
HandlingExceptions.Play();
CreatingExceptions.Play();